# Generated by Django 5.1.6 on 2025-02-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
        migrations.DeleteModel(
            name='Advantage',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='Personalization',
        ),
    ]
