# Generated by Django 5.0.6 on 2025-02-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0003_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.CharField(choices=[('in_stock', 'В наличии'), ('on_order', 'Под заказ')], default='in_stock', max_length=10, verbose_name='Наличие'),
        ),
        migrations.AddField(
            model_name='product',
            name='expected_delivery',
            field=models.CharField(blank=True, max_length=50, verbose_name='Срок поставки'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт.'), ('kg', 'кг')], default='pcs', max_length=3, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='product',
            name='wholesale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Оптовая цена'),
        ),
    ]
