# Generated by Django 5.1.6 on 2025-03-15 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0005_cart_cartitem_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('pcs', 'шт'), ('kg', 'кг')], default='pcs', max_length=3, verbose_name='Единица измерения'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/', verbose_name='Изображение продукта'),
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='samal.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Цвет продукта',
                'verbose_name_plural': 'Цвета продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50, verbose_name='Размер')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='samal.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Размер продукта',
                'verbose_name_plural': 'Размеры продуктов',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Количество')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samal.productcolor', verbose_name='Цвет')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='samal.product', verbose_name='Продукт')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='samal.productsize', verbose_name='Размер')),
            ],
            options={
                'verbose_name': 'Вариант товара',
                'verbose_name_plural': 'Варианты товаров',
                'unique_together': {('product', 'color', 'size')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='samal.productvariant', verbose_name='Вариант товара'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_variant')},
        ),
        migrations.CreateModel(
            name='WholesalePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оптовая цена')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wholesale_prices', to='samal.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Оптовая цена',
                'verbose_name_plural': 'Оптовые цены',
            },
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
    ]
