# Generated by Django 5.1.6 on 2025-03-31 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0006_remove_product_wholesale_price_alter_product_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('knitted_fabric', 'Трикотажное полотно'), ('knitwear_product', 'Готовое изделие из трикотажа')], default='simple', max_length=20, verbose_name='Тип продукта'),
        ),
    ]
