# Generated by Django 5.1.6 on 2025-03-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0007_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('knitted_fabric', 'Трикотажное полотно'), ('knitwear_product', 'Готовое изделие из трикотажа')], default='knitted_fabric', max_length=20, verbose_name='Тип продукта'),
        ),
    ]
