# Generated by Django 5.1.6 on 2025-04-01 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0009_remove_product_type_category_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('unisex', 'Унисекс'), ('male', 'Мужской'), ('female', 'Женский'), ('children', 'Детский')], default='unisex', max_length=10, verbose_name='Пол'),
        ),
    ]
