# Generated by Django 5.1.6 on 2025-04-12 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0010_product_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL, например, sewing, embroidery, printing', unique=True)),
                ('title', models.CharField(help_text='Название услуги', max_length=200)),
                ('description', models.TextField(help_text='Подробное описание услуги')),
                ('image', models.ImageField(blank=True, help_text='Изображение услуги', null=True, upload_to='services/')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
