# Generated by Django 5.1.6 on 2025-04-12 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0011_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug',
            field=models.SlugField(help_text='Уникальный идентификатор для URL, например: sewing, embroidery, printing', unique=True),
        ),
    ]
