# Generated by Django 5.1.6 on 2025-04-12 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0012_alter_service_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для варианта, например: option1')),
                ('title', models.CharField(help_text='Название варианта услуги', max_length=200)),
                ('description', models.TextField(help_text='Подробное описание варианта')),
                ('image', models.ImageField(blank=True, help_text='Изображение варианта', null=True, upload_to='services/variants/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='samal.service')),
            ],
            options={
                'verbose_name': 'Вариант услуги',
                'verbose_name_plural': 'Варианты услуг',
            },
        ),
    ]
