# Generated by Django 5.1.6 on 2025-04-17 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0013_servicevariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Изображение варианта услуги', upload_to='services/variants/images/')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='samal.servicevariant')),
            ],
            options={
                'verbose_name': 'Изображение варианта услуги',
                'verbose_name_plural': 'Изображения вариантов услуг',
            },
        ),
    ]
