# Generated by Django 5.2.1 on 2025-05-16 08:56

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samal', '0014_servicevariantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='color',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product', chained_model_field='product', on_delete=django.db.models.deletion.CASCADE, to='samal.productcolor'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='size',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='product', chained_model_field='product', on_delete=django.db.models.deletion.CASCADE, to='samal.productsize'),
        ),
    ]
